### ISSUE TITLE
Outputs do not take into account when working with an existing subnet

### ISSUE THREAD

**Issue by alexandrud** [Azure/terraform-azurerm-vnet-gateway#23]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Greenfield/Brownfield provisioning

greenfield

### Terraform Version

1.4.7

### Module Version

0.1.4

### AzureRM Provider Version

3.79.0

### Affected Resource(s)/Data Source(s)

outputs

### Terraform Configuration Files

```hcl
When you give it an existing subnet the resource azurerm_subnet "vgw" will not run so the output fails.
```

### tfvars variables values

```hcl
{
  "resource_group_location": "italynorth",
  "resource_group_name": "some_name",
  "subnet_id": "/subscriptions/<some_subscription>/resourceGroups/rg/providers/Microsoft.Network/virtualNetworks/vnet/subnets/subnet_name",
  "tags": {
    "Creator": "tf",
    "Environment": "prod",
    "Inventory": "bla",
    "Role": "vpn"
  },
  "virtual_network_name": "bla-prod-tf-vpc"
}
```

### Debug Output/Panic Output

```shell
Error: Error in function call
│ 
│   on .terraform/modules/vgw/outputs.tf line 35, in output "subnet":
│   35:     name = try(azurerm_subnet.vgw[0].name)
│     ├────────────────
│     │ while calling try(expressions...)
│     │ azurerm_subnet.vgw is empty tuple
```

### Expected Behaviour

The module should work even when you give it a "subnet_id".

### Actual Behaviour

The module crashes when you give it a "subnet_id".

### Steps to Reproduce

Run the module with "subnet_id" set.

### Important Factoids

None

### References

None

**Comment by luke-taylor** [comment]
Thanks for raising, will get this change implemented for the next release.
